### ISSUE TITLE
Not on Packagist

### ISSUE THREAD

**Issue by willwashburn** [cchiles/laravel-rackspace-cloudqueue#1]
I noticed this was not on Packagist so I went ahead and added it (https://packagist.org/packages/cchiles/laravel-rackspace-cloudqueue)

The readme says to use 1.0, but it looks like there is nothing tagged there. Is this still in development?

I'd be willing to take over the repo to support it if you're interested!

**Comment by cchiles** [comment]
@willwashburn: Thanks for adding to Packagist. I developed this for a project, but I haven't needed to do much in terms up new features and support. If you want to take it over and support it, I'd be more than happy to transfer it.

**Comment by willwashburn** [comment]
Sure thing! If you want to transfer it to @tailwind we'll be happy to support it

**Comment by cchiles** [comment]
I just tried to transfer it, but I don't have admin access within @tailwind. Github requires that to transfer to an organization. https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization

**Comment by willwashburn** [comment]
weird, ok want to just transfer it to me and I can transfer it over? Thanks for the help with this!

**Comment by cchiles** [comment]
It looks like you already have a fork of it, so it won't allow it because the repos are the same name.

**Comment by willwashburn** [comment]
Ha, figures. Sorry man. I just deleted it. Should work now.

**Comment by cchiles** [comment]
All set. Request sent!

**Comment by willwashburn** [comment]
Thanks @cchiles!
